# Create a Bike (POST)
### not working
POST http://localhost:8090/bikes
Content-Type: application/json

{
  "model": "Mountain 3000",
  "year": 2024,
  "engineCapacity": 150.0,
  "weight": 10.5,
  "userId": 1
}

### Get a specific Bike (GET)
GET http://localhost:8090/bikes/3

### Get all Bikes (GET)
GET http://localhost:8090/bikes

### Update a Bike (PUT)
### not working the many to many
PUT http://localhost:8090/bikes/3
Content-Type: application/json

{
"model": "Mountain 3500",
"year": 2025,
"engineCapacity": 200.0,
"weight": 11.5,
"userId": 2
}

### Delete a Bike (DELETE)
DELETE http://localhost:8090/bikes/21
