# Create a Brand (POST)
### not working
POST http://localhost:8090/brands
Content-Type: application/json

{
  "name": "Giant"
}

### Get a specific Brand (GET)
GET http://localhost:8090/brands/2

### Get all Brands (GET)
GET http://localhost:8090/brands

### Update a Brand (PUT)
PUT http://localhost:8090/brands/3
Content-Type: application/json

{
"name": "Trek"
}

### Delete a Brand (DELETE)
DELETE http://localhost:8090/brands/2
