GET http://localhost:8080/races/1

###
GET http://localhost:8080/races

###
DELETE http://localhost:8080/races/2

###
POST http://localhost:8080/races
Content-Type: application/json

{
  "circuitId": 1,
  "raceName": "Grand Prix",
  "raceDate": "2024-11-15",
  "drivers": []
}
### NOT WORKING
POST http://localhost:8080/races
Content-Type: application/json

{
  "circuitId": 1,
  "raceName": "Grand Prix",
  "raceDate": "2024-11-15",
  "drivers": [
    {"driverId": 1, "position": 1},
    {"driverId": 2, "position": 2}
  ]
}

###
PUT http://localhost:8080/races/7
Content-Type: application/json

{
  "circuitId": 1,
  "raceName": "Updated Grand Prix",
  "raceDate": "2024-12-01",
  "drivers": []
}

### NOT WORKING
PUT http://localhost:8080/races/2
Content-Type: application/json

{
  "circuitId": 1,
  "raceName": "Updated Grand Prix",
  "raceDate": "2024-12-01",
  "drivers": [
    {"driverId": 1, "position": 1},
    {"driverId": 3, "position": 2}
  ]
}